2024-11-17 18:25:34.608 UTC [1614343] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.3.0, 64-bit
2024-11-17 18:25:34.615 UTC [1614343] LOG:  listening on Unix socket "/home/cb/code/stk-todo-app-sql/test/pgdata/.s.PGSQL.5432"
2024-11-17 18:25:34.635 UTC [1614346] LOG:  database system was shut down at 2024-11-17 18:25:34 UTC
2024-11-17 18:25:34.644 UTC [1614343] LOG:  database system is ready to accept connections
2024-11-17 18:25:34.949 UTC [1614398] ERROR:  INSERT has more target columns than expressions at character 1274
2024-11-17 18:25:34.949 UTC [1614398] STATEMENT:  
	
	CREATE OR REPLACE FUNCTION private.t1010_created_updated()
	RETURNS TRIGGER AS $$
	DECLARE
	    current_user_v uuid;
	    psql_user_v text;
	BEGIN
	
	    RAISE EXCEPTION '...I AM HERE...';
	    BEGIN
	        SELECT current_setting('stk.session', true)::json->>'psql_user' INTO psql_user_v;
	    EXCEPTION
	        WHEN OTHERS THEN
	            psql_user_v := 'unknown';
	    END;
	
	    SELECT stk_actor_uu
	    FROM private.stk_actor
	    WHERE psql_user = psql_user_v
	    INTO current_user_v;
	    
	    IF current_user_v IS NULL THEN 
	        RAISE EXCEPTION 'no user found in session - current_user_v';
	    END IF;
	
	    IF TG_OP = 'INSERT' THEN
	        NEW.created = now();
	        NEW.updated = now();
	        NEW.created_by_uu = current_user_v;
	        NEW.updated_by_uu = current_user_v;
	    ELSIF TG_OP = 'UPDATE' THEN
	        NEW.created = OLD.created;
	        NEW.updated = now();
	        NEW.created_by_uu = OLD.created_by_uu;
	        NEW.updated_by_uu = current_user_v;
	    END IF;
	
	    RETURN NEW;
	END;
	$$ LANGUAGE plpgsql
	SECURITY DEFINER;
	COMMENT ON FUNCTION private.t1010_created_updated() IS 'manages automatic updates to created,updated,created_by_uu and updated_by_uu';
	
	insert into private.stk_trigger_mgt (function_name_prefix,function_name_root,table_name,is_include,is_exclude) values (1010,'created_updated','stk_delme','BEFORE INSERT OR UPDATE OR DELETE');
	
	select private.stk_trigger_create();
	
2024-11-17 18:25:34.949 UTC [1614398] LOG:  could not receive data from client: Connection reset by peer
2024-11-17 18:30:34.696 UTC [1614344] LOG:  checkpoint starting: time
2024-11-17 18:32:17.600 UTC [1614344] LOG:  checkpoint complete: wrote 1027 buffers (6.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=102.741 s, sync=0.130 s, total=102.904 s; sync files=354, longest=0.007 s, average=0.001 s; distance=4758 kB, estimate=4758 kB; lsn=0/1994F60, redo lsn=0/1994F28
